language: node_js
node_js:
  - 8 

before_install:
  - npm i -g npm@latest
  - npm install semantic-ui 
  - npm install gulp-cli -g

cache:
  directories:
    - "node_modules"
    - "semantic"

install: 
  - npm install
  - cd semantic/
  - gulp build
  - cd ..

before_script: npm run build

script: jest
